//SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/**
 * @title Interface standard that implement attestation contracts whose verification logic can be implemented
 * both on-chain and with ZK proofs
 * @notice The interface simply provides two verification methods for a given attestation input.
 * The user can either pay a possibly hefty gas cost to fully verify an attestation fully on-chain
 * OR
 * verifies SNARK proof generated by a program execution of the attestation verification in ZK co-processors
 */
interface IAttestation {
    /**
     * @notice full on-chain verification for an attestation
     * @dev must define the structure of inputs/outputs, to be serialized and passed to this method
     * @param input - serialized in raw bytes
     * @return success - whether the quote has been successfully verified or not
     * @return output - the output upon completion of verification. The output data may require post-processing by the consumer.
     * For verification failures, the output is simply a UTF-8 encoded string, describing the reason for failure.
     * @dev can directly type-cast the failed output as a string
     */
    function verifyAndAttestOnChain(bytes calldata input) external returns (bool success, bytes memory output);

    /**
     * @notice verifies an attestation using SNARK proofs
     * @param output - the output produced by the program executed in a zkVM
     * @param proofBytes - the proof of execution
     */
    function verifyAndAttestWithZKProof(bytes calldata output, bytes calldata proofBytes)
        external
        returns (bool success, bytes memory verifiedOutput);
}
