[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
automata-on-chain-pccs = "EBV7xychBtcjcDfQbXtTpZE8zyrL8BP9VhG7Fb5zaMab"
automata_dcap_verifier = "P33BtU5EDMHCVexoG4iv3ru9tC9v4CrFWFSgnEdFaAB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"

[[test.genesis]]
address = "3rp28FnaSDUsrwDHiggLFY12dVKvRovNbSs8iAKEFKmv"
program = "tests/test-programs/solana_zk.so"
upgradeable = true