[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
script = 'forge-script'
test = 'forge-test'
cache_path = 'cache_forge'
fs_permissions = [{ access = "read", path = "./" }]
remappings = [
    "solady/=lib/automata-on-chain-pccs/lib/solady/src/",
    "p256-verifier/=lib/automata-on-chain-pccs/lib/p256-verifier/src/",
    "@automata-network/on-chain-pccs/=lib/automata-on-chain-pccs/src/",
]
solc = "0.8.27"
optimizer = true
optimizer_runs = 200

# Useful link: https://github.com/foundry-rs/foundry/issues/3507
viaIR = true
evm_version = "paris"

ffi = true

[etherscan]
holesky = { key = "${ETHERSCAN_OG_API_KEY}", url = "https://api-holesky.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_OG_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
mainnet = { key = "${ETHERSCAN_OG_API_KEY}", url = "https://api.etherscan.io/api" }
