/**

Generated by the following Solidity interface...
```solidity
interface IPckDao {
    type CA is uint8;

    function getCert(string memory qeid, string memory platformCpuSvn, string memory platformPceSvn, string memory pceid) external view returns (bytes memory pckCert);
    function getCerts(string memory qeid, string memory pceid) external view returns (string[] memory tcbms, bytes[] memory pckCerts);
    function getPckCertChain(CA ca) external view returns (bytes memory intermediateCert, bytes memory rootCert);
    function getPlatformTcbByIdAndSvns(string memory qeid, string memory pceid, string memory platformCpuSvn, string memory platformPceSvn) external view returns (string memory tcbm);
    function upsertPckCert(CA ca, string memory qeid, string memory pceid, string memory tcbm, bytes memory cert) external returns (bytes32 attestationId);
    function upsertPlatformTcbs(string memory qeid, string memory pceid, string memory platformCpuSvn, string memory platformPceSvn, string memory tcbm) external returns (bytes32);
}
```

...which was generated by the following JSON ABI:
```json
[
  {
    "type": "function",
    "name": "getCert",
    "inputs": [
      {
        "name": "qeid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "platformCpuSvn",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "platformPceSvn",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "pceid",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "pckCert",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCerts",
    "inputs": [
      {
        "name": "qeid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "pceid",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "tcbms",
        "type": "string[]",
        "internalType": "string[]"
      },
      {
        "name": "pckCerts",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPckCertChain",
    "inputs": [
      {
        "name": "ca",
        "type": "uint8",
        "internalType": "enum CA"
      }
    ],
    "outputs": [
      {
        "name": "intermediateCert",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "rootCert",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPlatformTcbByIdAndSvns",
    "inputs": [
      {
        "name": "qeid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "pceid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "platformCpuSvn",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "platformPceSvn",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "tcbm",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "upsertPckCert",
    "inputs": [
      {
        "name": "ca",
        "type": "uint8",
        "internalType": "enum CA"
      },
      {
        "name": "qeid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "pceid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "tcbm",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "cert",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "attestationId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "upsertPlatformTcbs",
    "inputs": [
      {
        "name": "qeid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "pceid",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "platformCpuSvn",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "platformPceSvn",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "tcbm",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  }
]
```*/
#[allow(
    non_camel_case_types,
    non_snake_case,
    clippy::pub_underscore_fields,
    clippy::style,
    clippy::empty_structs_with_brackets
)]
pub mod IPckDao {
    use super::*;
    use alloy::sol_types as alloy_sol_types;
    /// The creation / init bytecode of the contract.
    ///
    /// ```text
    ///0x
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"",
    );
    /// The runtime bytecode of the contract, as deployed on the network.
    ///
    /// ```text
    ///0x
    /// ```
    #[rustfmt::skip]
    #[allow(clippy::all)]
    pub static DEPLOYED_BYTECODE: alloy_sol_types::private::Bytes = alloy_sol_types::private::Bytes::from_static(
        b"",
    );
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct CA(u8);
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        #[automatically_derived]
        impl alloy_sol_types::private::SolTypeValue<CA> for u8 {
            #[inline]
            fn stv_to_tokens(
                &self,
            ) -> <alloy::sol_types::sol_data::Uint<
                8,
            > as alloy_sol_types::SolType>::Token<'_> {
                alloy_sol_types::private::SolTypeValue::<
                    alloy::sol_types::sol_data::Uint<8>,
                >::stv_to_tokens(self)
            }
            #[inline]
            fn stv_eip712_data_word(&self) -> alloy_sol_types::Word {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::SolType>::tokenize(self)
                    .0
            }
            #[inline]
            fn stv_abi_encode_packed_to(
                &self,
                out: &mut alloy_sol_types::private::Vec<u8>,
            ) {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::SolType>::abi_encode_packed_to(self, out)
            }
            #[inline]
            fn stv_abi_packed_encoded_size(&self) -> usize {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::SolType>::abi_encoded_size(self)
            }
        }
        impl CA {
            /// The Solidity type name.
            pub const NAME: &'static str = stringify!(@ name);
            /// Convert from the underlying value type.
            #[inline]
            pub const fn from_underlying(value: u8) -> Self {
                Self(value)
            }
            /// Return the underlying value.
            #[inline]
            pub const fn into_underlying(self) -> u8 {
                self.0
            }
            /// Return the single encoding of this value, delegating to the
            /// underlying type.
            #[inline]
            pub fn abi_encode(&self) -> alloy_sol_types::private::Vec<u8> {
                <Self as alloy_sol_types::SolType>::abi_encode(&self.0)
            }
            /// Return the packed encoding of this value, delegating to the
            /// underlying type.
            #[inline]
            pub fn abi_encode_packed(&self) -> alloy_sol_types::private::Vec<u8> {
                <Self as alloy_sol_types::SolType>::abi_encode_packed(&self.0)
            }
        }
        #[automatically_derived]
        impl From<u8> for CA {
            fn from(value: u8) -> Self {
                Self::from_underlying(value)
            }
        }
        #[automatically_derived]
        impl From<CA> for u8 {
            fn from(value: CA) -> Self {
                value.into_underlying()
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolType for CA {
            type RustType = u8;
            type Token<'a> = <alloy::sol_types::sol_data::Uint<
                8,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SOL_NAME: &'static str = Self::NAME;
            const ENCODED_SIZE: Option<usize> = <alloy::sol_types::sol_data::Uint<
                8,
            > as alloy_sol_types::SolType>::ENCODED_SIZE;
            const PACKED_ENCODED_SIZE: Option<usize> = <alloy::sol_types::sol_data::Uint<
                8,
            > as alloy_sol_types::SolType>::PACKED_ENCODED_SIZE;
            #[inline]
            fn valid_token(token: &Self::Token<'_>) -> bool {
                Self::type_check(token).is_ok()
            }
            #[inline]
            fn type_check(token: &Self::Token<'_>) -> alloy_sol_types::Result<()> {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::SolType>::type_check(token)
            }
            #[inline]
            fn detokenize(token: Self::Token<'_>) -> Self::RustType {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::SolType>::detokenize(token)
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::EventTopic for CA {
            #[inline]
            fn topic_preimage_length(rust: &Self::RustType) -> usize {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::EventTopic>::topic_preimage_length(rust)
            }
            #[inline]
            fn encode_topic_preimage(
                rust: &Self::RustType,
                out: &mut alloy_sol_types::private::Vec<u8>,
            ) {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::EventTopic>::encode_topic_preimage(rust, out)
            }
            #[inline]
            fn encode_topic(
                rust: &Self::RustType,
            ) -> alloy_sol_types::abi::token::WordToken {
                <alloy::sol_types::sol_data::Uint<
                    8,
                > as alloy_sol_types::EventTopic>::encode_topic(rust)
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `getCert(string,string,string,string)` and selector `0x3c7d7114`.
```solidity
function getCert(string memory qeid, string memory platformCpuSvn, string memory platformPceSvn, string memory pceid) external view returns (bytes memory pckCert);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getCertCall {
        #[allow(missing_docs)]
        pub qeid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub platformCpuSvn: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub platformPceSvn: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub pceid: alloy::sol_types::private::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`getCert(string,string,string,string)`](getCertCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getCertReturn {
        #[allow(missing_docs)]
        pub pckCert: alloy::sol_types::private::Bytes,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getCertCall> for UnderlyingRustTuple<'_> {
                fn from(value: getCertCall) -> Self {
                    (value.qeid, value.platformCpuSvn, value.platformPceSvn, value.pceid)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for getCertCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        qeid: tuple.0,
                        platformCpuSvn: tuple.1,
                        platformPceSvn: tuple.2,
                        pceid: tuple.3,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::Bytes,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::Bytes,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getCertReturn> for UnderlyingRustTuple<'_> {
                fn from(value: getCertReturn) -> Self {
                    (value.pckCert,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for getCertReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { pckCert: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for getCertCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = alloy::sol_types::private::Bytes;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::Bytes,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "getCert(string,string,string,string)";
            const SELECTOR: [u8; 4] = [60u8, 125u8, 113u8, 20u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.qeid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.platformCpuSvn,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.platformPceSvn,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.pceid,
                    ),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::Bytes as alloy_sol_types::SolType>::tokenize(
                        ret,
                    ),
                )
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(|r| {
                        let r: getCertReturn = r.into();
                        r.pckCert
                    })
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(|r| {
                        let r: getCertReturn = r.into();
                        r.pckCert
                    })
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `getCerts(string,string)` and selector `0x28685839`.
```solidity
function getCerts(string memory qeid, string memory pceid) external view returns (string[] memory tcbms, bytes[] memory pckCerts);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getCertsCall {
        #[allow(missing_docs)]
        pub qeid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub pceid: alloy::sol_types::private::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`getCerts(string,string)`](getCertsCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getCertsReturn {
        #[allow(missing_docs)]
        pub tcbms: alloy::sol_types::private::Vec<alloy::sol_types::private::String>,
        #[allow(missing_docs)]
        pub pckCerts: alloy::sol_types::private::Vec<alloy::sol_types::private::Bytes>,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getCertsCall> for UnderlyingRustTuple<'_> {
                fn from(value: getCertsCall) -> Self {
                    (value.qeid, value.pceid)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for getCertsCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        qeid: tuple.0,
                        pceid: tuple.1,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Array<alloy::sol_types::sol_data::String>,
                alloy::sol_types::sol_data::Array<alloy::sol_types::sol_data::Bytes>,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::Vec<alloy::sol_types::private::String>,
                alloy::sol_types::private::Vec<alloy::sol_types::private::Bytes>,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getCertsReturn> for UnderlyingRustTuple<'_> {
                fn from(value: getCertsReturn) -> Self {
                    (value.tcbms, value.pckCerts)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for getCertsReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        tcbms: tuple.0,
                        pckCerts: tuple.1,
                    }
                }
            }
        }
        impl getCertsReturn {
            fn _tokenize(
                &self,
            ) -> <getCertsCall as alloy_sol_types::SolCall>::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::Array<
                        alloy::sol_types::sol_data::String,
                    > as alloy_sol_types::SolType>::tokenize(&self.tcbms),
                    <alloy::sol_types::sol_data::Array<
                        alloy::sol_types::sol_data::Bytes,
                    > as alloy_sol_types::SolType>::tokenize(&self.pckCerts),
                )
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for getCertsCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = getCertsReturn;
            type ReturnTuple<'a> = (
                alloy::sol_types::sol_data::Array<alloy::sol_types::sol_data::String>,
                alloy::sol_types::sol_data::Array<alloy::sol_types::sol_data::Bytes>,
            );
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "getCerts(string,string)";
            const SELECTOR: [u8; 4] = [40u8, 104u8, 88u8, 57u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.qeid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.pceid,
                    ),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                getCertsReturn::_tokenize(ret)
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(Into::into)
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(Into::into)
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `getPckCertChain(uint8)` and selector `0x48ac8059`.
```solidity
function getPckCertChain(CA ca) external view returns (bytes memory intermediateCert, bytes memory rootCert);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getPckCertChainCall {
        #[allow(missing_docs)]
        pub ca: <CA as alloy::sol_types::SolType>::RustType,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`getPckCertChain(uint8)`](getPckCertChainCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getPckCertChainReturn {
        #[allow(missing_docs)]
        pub intermediateCert: alloy::sol_types::private::Bytes,
        #[allow(missing_docs)]
        pub rootCert: alloy::sol_types::private::Bytes,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (CA,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                <CA as alloy::sol_types::SolType>::RustType,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getPckCertChainCall> for UnderlyingRustTuple<'_> {
                fn from(value: getPckCertChainCall) -> Self {
                    (value.ca,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for getPckCertChainCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { ca: tuple.0 }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::Bytes,
                alloy::sol_types::sol_data::Bytes,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::Bytes,
                alloy::sol_types::private::Bytes,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getPckCertChainReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: getPckCertChainReturn) -> Self {
                    (value.intermediateCert, value.rootCert)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for getPckCertChainReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        intermediateCert: tuple.0,
                        rootCert: tuple.1,
                    }
                }
            }
        }
        impl getPckCertChainReturn {
            fn _tokenize(
                &self,
            ) -> <getPckCertChainCall as alloy_sol_types::SolCall>::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::Bytes as alloy_sol_types::SolType>::tokenize(
                        &self.intermediateCert,
                    ),
                    <alloy::sol_types::sol_data::Bytes as alloy_sol_types::SolType>::tokenize(
                        &self.rootCert,
                    ),
                )
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for getPckCertChainCall {
            type Parameters<'a> = (CA,);
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = getPckCertChainReturn;
            type ReturnTuple<'a> = (
                alloy::sol_types::sol_data::Bytes,
                alloy::sol_types::sol_data::Bytes,
            );
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "getPckCertChain(uint8)";
            const SELECTOR: [u8; 4] = [72u8, 172u8, 128u8, 89u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (<CA as alloy_sol_types::SolType>::tokenize(&self.ca),)
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                getPckCertChainReturn::_tokenize(ret)
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(Into::into)
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(Into::into)
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `getPlatformTcbByIdAndSvns(string,string,string,string)` and selector `0x7eb619c7`.
```solidity
function getPlatformTcbByIdAndSvns(string memory qeid, string memory pceid, string memory platformCpuSvn, string memory platformPceSvn) external view returns (string memory tcbm);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getPlatformTcbByIdAndSvnsCall {
        #[allow(missing_docs)]
        pub qeid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub pceid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub platformCpuSvn: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub platformPceSvn: alloy::sol_types::private::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`getPlatformTcbByIdAndSvns(string,string,string,string)`](getPlatformTcbByIdAndSvnsCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct getPlatformTcbByIdAndSvnsReturn {
        #[allow(missing_docs)]
        pub tcbm: alloy::sol_types::private::String,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getPlatformTcbByIdAndSvnsCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: getPlatformTcbByIdAndSvnsCall) -> Self {
                    (value.qeid, value.pceid, value.platformCpuSvn, value.platformPceSvn)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for getPlatformTcbByIdAndSvnsCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        qeid: tuple.0,
                        pceid: tuple.1,
                        platformCpuSvn: tuple.2,
                        platformPceSvn: tuple.3,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::String,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::String,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<getPlatformTcbByIdAndSvnsReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: getPlatformTcbByIdAndSvnsReturn) -> Self {
                    (value.tcbm,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for getPlatformTcbByIdAndSvnsReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { tcbm: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for getPlatformTcbByIdAndSvnsCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = alloy::sol_types::private::String;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::String,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "getPlatformTcbByIdAndSvns(string,string,string,string)";
            const SELECTOR: [u8; 4] = [126u8, 182u8, 25u8, 199u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.qeid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.pceid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.platformCpuSvn,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.platformPceSvn,
                    ),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        ret,
                    ),
                )
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(|r| {
                        let r: getPlatformTcbByIdAndSvnsReturn = r.into();
                        r.tcbm
                    })
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(|r| {
                        let r: getPlatformTcbByIdAndSvnsReturn = r.into();
                        r.tcbm
                    })
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `upsertPckCert(uint8,string,string,string,bytes)` and selector `0x5be0fa4b`.
```solidity
function upsertPckCert(CA ca, string memory qeid, string memory pceid, string memory tcbm, bytes memory cert) external returns (bytes32 attestationId);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct upsertPckCertCall {
        #[allow(missing_docs)]
        pub ca: <CA as alloy::sol_types::SolType>::RustType,
        #[allow(missing_docs)]
        pub qeid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub pceid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub tcbm: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub cert: alloy::sol_types::private::Bytes,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`upsertPckCert(uint8,string,string,string,bytes)`](upsertPckCertCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct upsertPckCertReturn {
        #[allow(missing_docs)]
        pub attestationId: alloy::sol_types::private::FixedBytes<32>,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                CA,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::Bytes,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                <CA as alloy::sol_types::SolType>::RustType,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::Bytes,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<upsertPckCertCall> for UnderlyingRustTuple<'_> {
                fn from(value: upsertPckCertCall) -> Self {
                    (value.ca, value.qeid, value.pceid, value.tcbm, value.cert)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for upsertPckCertCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        ca: tuple.0,
                        qeid: tuple.1,
                        pceid: tuple.2,
                        tcbm: tuple.3,
                        cert: tuple.4,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::FixedBytes<32>,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<upsertPckCertReturn> for UnderlyingRustTuple<'_> {
                fn from(value: upsertPckCertReturn) -> Self {
                    (value.attestationId,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>> for upsertPckCertReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { attestationId: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for upsertPckCertCall {
            type Parameters<'a> = (
                CA,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::Bytes,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = alloy::sol_types::private::FixedBytes<32>;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "upsertPckCert(uint8,string,string,string,bytes)";
            const SELECTOR: [u8; 4] = [91u8, 224u8, 250u8, 75u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <CA as alloy_sol_types::SolType>::tokenize(&self.ca),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.qeid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.pceid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.tcbm,
                    ),
                    <alloy::sol_types::sol_data::Bytes as alloy_sol_types::SolType>::tokenize(
                        &self.cert,
                    ),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::FixedBytes<
                        32,
                    > as alloy_sol_types::SolType>::tokenize(ret),
                )
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(|r| {
                        let r: upsertPckCertReturn = r.into();
                        r.attestationId
                    })
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(|r| {
                        let r: upsertPckCertReturn = r.into();
                        r.attestationId
                    })
            }
        }
    };
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    /**Function with signature `upsertPlatformTcbs(string,string,string,string,string)` and selector `0xc925d17a`.
```solidity
function upsertPlatformTcbs(string memory qeid, string memory pceid, string memory platformCpuSvn, string memory platformPceSvn, string memory tcbm) external returns (bytes32);
```*/
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct upsertPlatformTcbsCall {
        #[allow(missing_docs)]
        pub qeid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub pceid: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub platformCpuSvn: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub platformPceSvn: alloy::sol_types::private::String,
        #[allow(missing_docs)]
        pub tcbm: alloy::sol_types::private::String,
    }
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Default, Debug, PartialEq, Eq, Hash)]
    ///Container type for the return parameters of the [`upsertPlatformTcbs(string,string,string,string,string)`](upsertPlatformTcbsCall) function.
    #[allow(non_camel_case_types, non_snake_case, clippy::pub_underscore_fields)]
    #[derive(Clone)]
    pub struct upsertPlatformTcbsReturn {
        #[allow(missing_docs)]
        pub _0: alloy::sol_types::private::FixedBytes<32>,
    }
    #[allow(
        non_camel_case_types,
        non_snake_case,
        clippy::pub_underscore_fields,
        clippy::style
    )]
    const _: () = {
        use alloy::sol_types as alloy_sol_types;
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
                alloy::sol_types::private::String,
            );
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<upsertPlatformTcbsCall>
            for UnderlyingRustTuple<'_> {
                fn from(value: upsertPlatformTcbsCall) -> Self {
                    (
                        value.qeid,
                        value.pceid,
                        value.platformCpuSvn,
                        value.platformPceSvn,
                        value.tcbm,
                    )
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for upsertPlatformTcbsCall {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self {
                        qeid: tuple.0,
                        pceid: tuple.1,
                        platformCpuSvn: tuple.2,
                        platformPceSvn: tuple.3,
                        tcbm: tuple.4,
                    }
                }
            }
        }
        {
            #[doc(hidden)]
            #[allow(dead_code)]
            type UnderlyingSolTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
            #[doc(hidden)]
            type UnderlyingRustTuple<'a> = (alloy::sol_types::private::FixedBytes<32>,);
            #[cfg(test)]
            #[allow(dead_code, unreachable_patterns)]
            fn _type_assertion(
                _t: alloy_sol_types::private::AssertTypeEq<UnderlyingRustTuple>,
            ) {
                match _t {
                    alloy_sol_types::private::AssertTypeEq::<
                        <UnderlyingSolTuple as alloy_sol_types::SolType>::RustType,
                    >(_) => {}
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<upsertPlatformTcbsReturn>
            for UnderlyingRustTuple<'_> {
                fn from(value: upsertPlatformTcbsReturn) -> Self {
                    (value._0,)
                }
            }
            #[automatically_derived]
            #[doc(hidden)]
            impl ::core::convert::From<UnderlyingRustTuple<'_>>
            for upsertPlatformTcbsReturn {
                fn from(tuple: UnderlyingRustTuple<'_>) -> Self {
                    Self { _0: tuple.0 }
                }
            }
        }
        #[automatically_derived]
        impl alloy_sol_types::SolCall for upsertPlatformTcbsCall {
            type Parameters<'a> = (
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
                alloy::sol_types::sol_data::String,
            );
            type Token<'a> = <Self::Parameters<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            type Return = alloy::sol_types::private::FixedBytes<32>;
            type ReturnTuple<'a> = (alloy::sol_types::sol_data::FixedBytes<32>,);
            type ReturnToken<'a> = <Self::ReturnTuple<
                'a,
            > as alloy_sol_types::SolType>::Token<'a>;
            const SIGNATURE: &'static str = "upsertPlatformTcbs(string,string,string,string,string)";
            const SELECTOR: [u8; 4] = [201u8, 37u8, 209u8, 122u8];
            #[inline]
            fn new<'a>(
                tuple: <Self::Parameters<'a> as alloy_sol_types::SolType>::RustType,
            ) -> Self {
                tuple.into()
            }
            #[inline]
            fn tokenize(&self) -> Self::Token<'_> {
                (
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.qeid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.pceid,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.platformCpuSvn,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.platformPceSvn,
                    ),
                    <alloy::sol_types::sol_data::String as alloy_sol_types::SolType>::tokenize(
                        &self.tcbm,
                    ),
                )
            }
            #[inline]
            fn tokenize_returns(ret: &Self::Return) -> Self::ReturnToken<'_> {
                (
                    <alloy::sol_types::sol_data::FixedBytes<
                        32,
                    > as alloy_sol_types::SolType>::tokenize(ret),
                )
            }
            #[inline]
            fn abi_decode_returns(data: &[u8]) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence(data)
                    .map(|r| {
                        let r: upsertPlatformTcbsReturn = r.into();
                        r._0
                    })
            }
            #[inline]
            fn abi_decode_returns_validate(
                data: &[u8],
            ) -> alloy_sol_types::Result<Self::Return> {
                <Self::ReturnTuple<
                    '_,
                > as alloy_sol_types::SolType>::abi_decode_sequence_validate(data)
                    .map(|r| {
                        let r: upsertPlatformTcbsReturn = r.into();
                        r._0
                    })
            }
        }
    };
    ///Container for all the [`IPckDao`](self) function calls.
    #[derive(Clone)]
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive()]
    pub enum IPckDaoCalls {
        #[allow(missing_docs)]
        getCert(getCertCall),
        #[allow(missing_docs)]
        getCerts(getCertsCall),
        #[allow(missing_docs)]
        getPckCertChain(getPckCertChainCall),
        #[allow(missing_docs)]
        getPlatformTcbByIdAndSvns(getPlatformTcbByIdAndSvnsCall),
        #[allow(missing_docs)]
        upsertPckCert(upsertPckCertCall),
        #[allow(missing_docs)]
        upsertPlatformTcbs(upsertPlatformTcbsCall),
    }
    impl IPckDaoCalls {
        /// All the selectors of this enum.
        ///
        /// Note that the selectors might not be in the same order as the variants.
        /// No guarantees are made about the order of the selectors.
        ///
        /// Prefer using `SolInterface` methods instead.
        pub const SELECTORS: &'static [[u8; 4usize]] = &[
            [40u8, 104u8, 88u8, 57u8],
            [60u8, 125u8, 113u8, 20u8],
            [72u8, 172u8, 128u8, 89u8],
            [91u8, 224u8, 250u8, 75u8],
            [126u8, 182u8, 25u8, 199u8],
            [201u8, 37u8, 209u8, 122u8],
        ];
        /// The names of the variants in the same order as `SELECTORS`.
        pub const VARIANT_NAMES: &'static [&'static str] = &[
            ::core::stringify!(getCerts),
            ::core::stringify!(getCert),
            ::core::stringify!(getPckCertChain),
            ::core::stringify!(upsertPckCert),
            ::core::stringify!(getPlatformTcbByIdAndSvns),
            ::core::stringify!(upsertPlatformTcbs),
        ];
        /// The signatures in the same order as `SELECTORS`.
        pub const SIGNATURES: &'static [&'static str] = &[
            <getCertsCall as alloy_sol_types::SolCall>::SIGNATURE,
            <getCertCall as alloy_sol_types::SolCall>::SIGNATURE,
            <getPckCertChainCall as alloy_sol_types::SolCall>::SIGNATURE,
            <upsertPckCertCall as alloy_sol_types::SolCall>::SIGNATURE,
            <getPlatformTcbByIdAndSvnsCall as alloy_sol_types::SolCall>::SIGNATURE,
            <upsertPlatformTcbsCall as alloy_sol_types::SolCall>::SIGNATURE,
        ];
        /// Returns the signature for the given selector, if known.
        #[inline]
        pub fn signature_by_selector(
            selector: [u8; 4usize],
        ) -> ::core::option::Option<&'static str> {
            match Self::SELECTORS.binary_search(&selector) {
                ::core::result::Result::Ok(idx) => {
                    ::core::option::Option::Some(Self::SIGNATURES[idx])
                }
                ::core::result::Result::Err(_) => ::core::option::Option::None,
            }
        }
        /// Returns the enum variant name for the given selector, if known.
        #[inline]
        pub fn name_by_selector(
            selector: [u8; 4usize],
        ) -> ::core::option::Option<&'static str> {
            let sig = Self::signature_by_selector(selector)?;
            sig.split_once('(').map(|(name, _)| name)
        }
    }
    #[automatically_derived]
    impl alloy_sol_types::SolInterface for IPckDaoCalls {
        const NAME: &'static str = "IPckDaoCalls";
        const MIN_DATA_LENGTH: usize = 32usize;
        const COUNT: usize = 6usize;
        #[inline]
        fn selector(&self) -> [u8; 4] {
            match self {
                Self::getCert(_) => <getCertCall as alloy_sol_types::SolCall>::SELECTOR,
                Self::getCerts(_) => <getCertsCall as alloy_sol_types::SolCall>::SELECTOR,
                Self::getPckCertChain(_) => {
                    <getPckCertChainCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::getPlatformTcbByIdAndSvns(_) => {
                    <getPlatformTcbByIdAndSvnsCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::upsertPckCert(_) => {
                    <upsertPckCertCall as alloy_sol_types::SolCall>::SELECTOR
                }
                Self::upsertPlatformTcbs(_) => {
                    <upsertPlatformTcbsCall as alloy_sol_types::SolCall>::SELECTOR
                }
            }
        }
        #[inline]
        fn selector_at(i: usize) -> ::core::option::Option<[u8; 4]> {
            Self::SELECTORS.get(i).copied()
        }
        #[inline]
        fn valid_selector(selector: [u8; 4]) -> bool {
            Self::SELECTORS.binary_search(&selector).is_ok()
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw(
            selector: [u8; 4],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_SHIMS: &[fn(&[u8]) -> alloy_sol_types::Result<IPckDaoCalls>] = &[
                {
                    fn getCerts(data: &[u8]) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getCertsCall as alloy_sol_types::SolCall>::abi_decode_raw(data)
                            .map(IPckDaoCalls::getCerts)
                    }
                    getCerts
                },
                {
                    fn getCert(data: &[u8]) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getCertCall as alloy_sol_types::SolCall>::abi_decode_raw(data)
                            .map(IPckDaoCalls::getCert)
                    }
                    getCert
                },
                {
                    fn getPckCertChain(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getPckCertChainCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(IPckDaoCalls::getPckCertChain)
                    }
                    getPckCertChain
                },
                {
                    fn upsertPckCert(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <upsertPckCertCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(IPckDaoCalls::upsertPckCert)
                    }
                    upsertPckCert
                },
                {
                    fn getPlatformTcbByIdAndSvns(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getPlatformTcbByIdAndSvnsCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(IPckDaoCalls::getPlatformTcbByIdAndSvns)
                    }
                    getPlatformTcbByIdAndSvns
                },
                {
                    fn upsertPlatformTcbs(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <upsertPlatformTcbsCall as alloy_sol_types::SolCall>::abi_decode_raw(
                                data,
                            )
                            .map(IPckDaoCalls::upsertPlatformTcbs)
                    }
                    upsertPlatformTcbs
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            DECODE_SHIMS[idx](data)
        }
        #[inline]
        #[allow(non_snake_case)]
        fn abi_decode_raw_validate(
            selector: [u8; 4],
            data: &[u8],
        ) -> alloy_sol_types::Result<Self> {
            static DECODE_VALIDATE_SHIMS: &[fn(
                &[u8],
            ) -> alloy_sol_types::Result<IPckDaoCalls>] = &[
                {
                    fn getCerts(data: &[u8]) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getCertsCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IPckDaoCalls::getCerts)
                    }
                    getCerts
                },
                {
                    fn getCert(data: &[u8]) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getCertCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IPckDaoCalls::getCert)
                    }
                    getCert
                },
                {
                    fn getPckCertChain(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getPckCertChainCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IPckDaoCalls::getPckCertChain)
                    }
                    getPckCertChain
                },
                {
                    fn upsertPckCert(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <upsertPckCertCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IPckDaoCalls::upsertPckCert)
                    }
                    upsertPckCert
                },
                {
                    fn getPlatformTcbByIdAndSvns(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <getPlatformTcbByIdAndSvnsCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IPckDaoCalls::getPlatformTcbByIdAndSvns)
                    }
                    getPlatformTcbByIdAndSvns
                },
                {
                    fn upsertPlatformTcbs(
                        data: &[u8],
                    ) -> alloy_sol_types::Result<IPckDaoCalls> {
                        <upsertPlatformTcbsCall as alloy_sol_types::SolCall>::abi_decode_raw_validate(
                                data,
                            )
                            .map(IPckDaoCalls::upsertPlatformTcbs)
                    }
                    upsertPlatformTcbs
                },
            ];
            let Ok(idx) = Self::SELECTORS.binary_search(&selector) else {
                return Err(
                    alloy_sol_types::Error::unknown_selector(
                        <Self as alloy_sol_types::SolInterface>::NAME,
                        selector,
                    ),
                );
            };
            DECODE_VALIDATE_SHIMS[idx](data)
        }
        #[inline]
        fn abi_encoded_size(&self) -> usize {
            match self {
                Self::getCert(inner) => {
                    <getCertCall as alloy_sol_types::SolCall>::abi_encoded_size(inner)
                }
                Self::getCerts(inner) => {
                    <getCertsCall as alloy_sol_types::SolCall>::abi_encoded_size(inner)
                }
                Self::getPckCertChain(inner) => {
                    <getPckCertChainCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::getPlatformTcbByIdAndSvns(inner) => {
                    <getPlatformTcbByIdAndSvnsCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::upsertPckCert(inner) => {
                    <upsertPckCertCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
                Self::upsertPlatformTcbs(inner) => {
                    <upsertPlatformTcbsCall as alloy_sol_types::SolCall>::abi_encoded_size(
                        inner,
                    )
                }
            }
        }
        #[inline]
        fn abi_encode_raw(&self, out: &mut alloy_sol_types::private::Vec<u8>) {
            match self {
                Self::getCert(inner) => {
                    <getCertCall as alloy_sol_types::SolCall>::abi_encode_raw(inner, out)
                }
                Self::getCerts(inner) => {
                    <getCertsCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::getPckCertChain(inner) => {
                    <getPckCertChainCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::getPlatformTcbByIdAndSvns(inner) => {
                    <getPlatformTcbByIdAndSvnsCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::upsertPckCert(inner) => {
                    <upsertPckCertCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
                Self::upsertPlatformTcbs(inner) => {
                    <upsertPlatformTcbsCall as alloy_sol_types::SolCall>::abi_encode_raw(
                        inner,
                        out,
                    )
                }
            }
        }
    }
    use alloy::contract as alloy_contract;
    /**Creates a new wrapper around an on-chain [`IPckDao`](self) contract instance.

See the [wrapper's documentation](`IPckDaoInstance`) for more details.*/
    #[inline]
    pub const fn new<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(
        address: alloy_sol_types::private::Address,
        __provider: P,
    ) -> IPckDaoInstance<P, N> {
        IPckDaoInstance::<P, N>::new(address, __provider)
    }
    /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
    #[inline]
    pub fn deploy<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(
        __provider: P,
    ) -> impl ::core::future::Future<
        Output = alloy_contract::Result<IPckDaoInstance<P, N>>,
    > {
        IPckDaoInstance::<P, N>::deploy(__provider)
    }
    /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
    #[inline]
    pub fn deploy_builder<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    >(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
        IPckDaoInstance::<P, N>::deploy_builder(__provider)
    }
    /**A [`IPckDao`](self) instance.

Contains type-safe methods for interacting with an on-chain instance of the
[`IPckDao`](self) contract located at a given `address`, using a given
provider `P`.

If the contract bytecode is available (see the [`sol!`](alloy_sol_types::sol!)
documentation on how to provide it), the `deploy` and `deploy_builder` methods can
be used to deploy a new instance of the contract.

See the [module-level documentation](self) for all the available methods.*/
    #[derive(Clone)]
    pub struct IPckDaoInstance<P, N = alloy_contract::private::Ethereum> {
        address: alloy_sol_types::private::Address,
        provider: P,
        _network: ::core::marker::PhantomData<N>,
    }
    #[automatically_derived]
    impl<P, N> ::core::fmt::Debug for IPckDaoInstance<P, N> {
        #[inline]
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_tuple("IPckDaoInstance").field(&self.address).finish()
        }
    }
    /// Instantiation and getters/setters.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > IPckDaoInstance<P, N> {
        /**Creates a new wrapper around an on-chain [`IPckDao`](self) contract instance.

See the [wrapper's documentation](`IPckDaoInstance`) for more details.*/
        #[inline]
        pub const fn new(
            address: alloy_sol_types::private::Address,
            __provider: P,
        ) -> Self {
            Self {
                address,
                provider: __provider,
                _network: ::core::marker::PhantomData,
            }
        }
        /**Deploys this contract using the given `provider` and constructor arguments, if any.

Returns a new instance of the contract, if the deployment was successful.

For more fine-grained control over the deployment process, use [`deploy_builder`] instead.*/
        #[inline]
        pub async fn deploy(
            __provider: P,
        ) -> alloy_contract::Result<IPckDaoInstance<P, N>> {
            let call_builder = Self::deploy_builder(__provider);
            let contract_address = call_builder.deploy().await?;
            Ok(Self::new(contract_address, call_builder.provider))
        }
        /**Creates a `RawCallBuilder` for deploying this contract using the given `provider`
and constructor arguments, if any.

This is a simple wrapper around creating a `RawCallBuilder` with the data set to
the bytecode concatenated with the constructor's ABI-encoded arguments.*/
        #[inline]
        pub fn deploy_builder(__provider: P) -> alloy_contract::RawCallBuilder<P, N> {
            alloy_contract::RawCallBuilder::new_raw_deploy(
                __provider,
                ::core::clone::Clone::clone(&BYTECODE),
            )
        }
        /// Returns a reference to the address.
        #[inline]
        pub const fn address(&self) -> &alloy_sol_types::private::Address {
            &self.address
        }
        /// Sets the address.
        #[inline]
        pub fn set_address(&mut self, address: alloy_sol_types::private::Address) {
            self.address = address;
        }
        /// Sets the address and returns `self`.
        pub fn at(mut self, address: alloy_sol_types::private::Address) -> Self {
            self.set_address(address);
            self
        }
        /// Returns a reference to the provider.
        #[inline]
        pub const fn provider(&self) -> &P {
            &self.provider
        }
    }
    impl<P: ::core::clone::Clone, N> IPckDaoInstance<&P, N> {
        /// Clones the provider and returns a new instance with the cloned provider.
        #[inline]
        pub fn with_cloned_provider(self) -> IPckDaoInstance<P, N> {
            IPckDaoInstance {
                address: self.address,
                provider: ::core::clone::Clone::clone(&self.provider),
                _network: ::core::marker::PhantomData,
            }
        }
    }
    /// Function calls.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > IPckDaoInstance<P, N> {
        /// Creates a new call builder using this contract instance's provider and address.
        ///
        /// Note that the call can be any function call, not just those defined in this
        /// contract. Prefer using the other methods for building type-safe contract calls.
        pub fn call_builder<C: alloy_sol_types::SolCall>(
            &self,
            call: &C,
        ) -> alloy_contract::SolCallBuilder<&P, C, N> {
            alloy_contract::SolCallBuilder::new_sol(&self.provider, &self.address, call)
        }
        ///Creates a new call builder for the [`getCert`] function.
        pub fn getCert(
            &self,
            qeid: alloy::sol_types::private::String,
            platformCpuSvn: alloy::sol_types::private::String,
            platformPceSvn: alloy::sol_types::private::String,
            pceid: alloy::sol_types::private::String,
        ) -> alloy_contract::SolCallBuilder<&P, getCertCall, N> {
            self.call_builder(
                &getCertCall {
                    qeid,
                    platformCpuSvn,
                    platformPceSvn,
                    pceid,
                },
            )
        }
        ///Creates a new call builder for the [`getCerts`] function.
        pub fn getCerts(
            &self,
            qeid: alloy::sol_types::private::String,
            pceid: alloy::sol_types::private::String,
        ) -> alloy_contract::SolCallBuilder<&P, getCertsCall, N> {
            self.call_builder(&getCertsCall { qeid, pceid })
        }
        ///Creates a new call builder for the [`getPckCertChain`] function.
        pub fn getPckCertChain(
            &self,
            ca: <CA as alloy::sol_types::SolType>::RustType,
        ) -> alloy_contract::SolCallBuilder<&P, getPckCertChainCall, N> {
            self.call_builder(&getPckCertChainCall { ca })
        }
        ///Creates a new call builder for the [`getPlatformTcbByIdAndSvns`] function.
        pub fn getPlatformTcbByIdAndSvns(
            &self,
            qeid: alloy::sol_types::private::String,
            pceid: alloy::sol_types::private::String,
            platformCpuSvn: alloy::sol_types::private::String,
            platformPceSvn: alloy::sol_types::private::String,
        ) -> alloy_contract::SolCallBuilder<&P, getPlatformTcbByIdAndSvnsCall, N> {
            self.call_builder(
                &getPlatformTcbByIdAndSvnsCall {
                    qeid,
                    pceid,
                    platformCpuSvn,
                    platformPceSvn,
                },
            )
        }
        ///Creates a new call builder for the [`upsertPckCert`] function.
        pub fn upsertPckCert(
            &self,
            ca: <CA as alloy::sol_types::SolType>::RustType,
            qeid: alloy::sol_types::private::String,
            pceid: alloy::sol_types::private::String,
            tcbm: alloy::sol_types::private::String,
            cert: alloy::sol_types::private::Bytes,
        ) -> alloy_contract::SolCallBuilder<&P, upsertPckCertCall, N> {
            self.call_builder(
                &upsertPckCertCall {
                    ca,
                    qeid,
                    pceid,
                    tcbm,
                    cert,
                },
            )
        }
        ///Creates a new call builder for the [`upsertPlatformTcbs`] function.
        pub fn upsertPlatformTcbs(
            &self,
            qeid: alloy::sol_types::private::String,
            pceid: alloy::sol_types::private::String,
            platformCpuSvn: alloy::sol_types::private::String,
            platformPceSvn: alloy::sol_types::private::String,
            tcbm: alloy::sol_types::private::String,
        ) -> alloy_contract::SolCallBuilder<&P, upsertPlatformTcbsCall, N> {
            self.call_builder(
                &upsertPlatformTcbsCall {
                    qeid,
                    pceid,
                    platformCpuSvn,
                    platformPceSvn,
                    tcbm,
                },
            )
        }
    }
    /// Event filters.
    impl<
        P: alloy_contract::private::Provider<N>,
        N: alloy_contract::private::Network,
    > IPckDaoInstance<P, N> {
        /// Creates a new event filter using this contract instance's provider and address.
        ///
        /// Note that the type can be any event, not just those defined in this contract.
        /// Prefer using the other methods for building type-safe event filters.
        pub fn event_filter<E: alloy_sol_types::SolEvent>(
            &self,
        ) -> alloy_contract::Event<&P, E, N> {
            alloy_contract::Event::new_sol(&self.provider, &self.address)
        }
    }
}
