#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod r#i_automata_dcap_attestation;
pub mod r#i_enclave_identity_dao;
pub mod r#i_fmspc_tcb_dao;
pub mod r#i_pck_dao;
pub mod r#i_pcs_dao;
pub mod r#i_tcb_eval_dao;
pub mod r#ipccs_router;
