// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: artifact.proto

package sp1_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtifactStore_CreateArtifact_FullMethodName = "/artifact.ArtifactStore/CreateArtifact"
)

// ArtifactStoreClient is the client API for ArtifactStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtifactStoreClient interface {
	CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*CreateArtifactResponse, error)
}

type artifactStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactStoreClient(cc grpc.ClientConnInterface) ArtifactStoreClient {
	return &artifactStoreClient{cc}
}

func (c *artifactStoreClient) CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*CreateArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactStore_CreateArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactStoreServer is the server API for ArtifactStore service.
// All implementations must embed UnimplementedArtifactStoreServer
// for forward compatibility.
type ArtifactStoreServer interface {
	CreateArtifact(context.Context, *CreateArtifactRequest) (*CreateArtifactResponse, error)
	mustEmbedUnimplementedArtifactStoreServer()
}

// UnimplementedArtifactStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactStoreServer struct{}

func (UnimplementedArtifactStoreServer) CreateArtifact(context.Context, *CreateArtifactRequest) (*CreateArtifactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArtifact not implemented")
}
func (UnimplementedArtifactStoreServer) mustEmbedUnimplementedArtifactStoreServer() {}
func (UnimplementedArtifactStoreServer) testEmbeddedByValue()                       {}

// UnsafeArtifactStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactStoreServer will
// result in compilation errors.
type UnsafeArtifactStoreServer interface {
	mustEmbedUnimplementedArtifactStoreServer()
}

func RegisterArtifactStoreServer(s grpc.ServiceRegistrar, srv ArtifactStoreServer) {
	// If the following call pancis, it indicates UnimplementedArtifactStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactStore_ServiceDesc, srv)
}

func _ArtifactStore_CreateArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactStoreServer).CreateArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactStore_CreateArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactStoreServer).CreateArtifact(ctx, req.(*CreateArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactStore_ServiceDesc is the grpc.ServiceDesc for ArtifactStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artifact.ArtifactStore",
	HandlerType: (*ArtifactStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArtifact",
			Handler:    _ArtifactStore_CreateArtifact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "artifact.proto",
}
