// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: artifact.proto

package sp1_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactType int32

const (
	ArtifactType_UnspecifiedArtifactType ArtifactType = 0
	// / A program artifact.
	ArtifactType_Program ArtifactType = 1
	// / A stdin artifact.
	ArtifactType_Stdin ArtifactType = 2
	// / A proof artifact.
	ArtifactType_Proof ArtifactType = 3
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "UnspecifiedArtifactType",
		1: "Program",
		2: "Stdin",
		3: "Proof",
	}
	ArtifactType_value = map[string]int32{
		"UnspecifiedArtifactType": 0,
		"Program":                 1,
		"Stdin":                   2,
		"Proof":                   3,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_artifact_proto_enumTypes[0]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

type CreateArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	ArtifactType  ArtifactType           `protobuf:"varint,2,opt,name=artifact_type,json=artifactType,proto3,enum=artifact.ArtifactType" json:"artifact_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArtifactRequest) Reset() {
	*x = CreateArtifactRequest{}
	mi := &file_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactRequest) ProtoMessage() {}

func (x *CreateArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactRequest.ProtoReflect.Descriptor instead.
func (*CreateArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *CreateArtifactRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *CreateArtifactRequest) GetArtifactType() ArtifactType {
	if x != nil {
		return x.ArtifactType
	}
	return ArtifactType_UnspecifiedArtifactType
}

type CreateArtifactResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUri          string                 `protobuf:"bytes,1,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	ArtifactPresignedUrl string                 `protobuf:"bytes,2,opt,name=artifact_presigned_url,json=artifactPresignedUrl,proto3" json:"artifact_presigned_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateArtifactResponse) Reset() {
	*x = CreateArtifactResponse{}
	mi := &file_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArtifactResponse) ProtoMessage() {}

func (x *CreateArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArtifactResponse.ProtoReflect.Descriptor instead.
func (*CreateArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArtifactResponse) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *CreateArtifactResponse) GetArtifactPresignedUrl() string {
	if x != nil {
		return x.ArtifactPresignedUrl
	}
	return ""
}

var File_artifact_proto protoreflect.FileDescriptor

const file_artifact_proto_rawDesc = "" +
	"\n" +
	"\x0eartifact.proto\x12\bartifact\"r\n" +
	"\x15CreateArtifactRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12;\n" +
	"\rartifact_type\x18\x02 \x01(\x0e2\x16.artifact.ArtifactTypeR\fartifactType\"q\n" +
	"\x16CreateArtifactResponse\x12!\n" +
	"\fartifact_uri\x18\x01 \x01(\tR\vartifactUri\x124\n" +
	"\x16artifact_presigned_url\x18\x02 \x01(\tR\x14artifactPresignedUrl*N\n" +
	"\fArtifactType\x12\x1b\n" +
	"\x17UnspecifiedArtifactType\x10\x00\x12\v\n" +
	"\aProgram\x10\x01\x12\t\n" +
	"\x05Stdin\x10\x02\x12\t\n" +
	"\x05Proof\x10\x032d\n" +
	"\rArtifactStore\x12S\n" +
	"\x0eCreateArtifact\x12\x1f.artifact.CreateArtifactRequest\x1a .artifact.CreateArtifactResponseB\rZ\v./sp1_protob\x06proto3"

var (
	file_artifact_proto_rawDescOnce sync.Once
	file_artifact_proto_rawDescData []byte
)

func file_artifact_proto_rawDescGZIP() []byte {
	file_artifact_proto_rawDescOnce.Do(func() {
		file_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)))
	})
	return file_artifact_proto_rawDescData
}

var file_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_artifact_proto_goTypes = []any{
	(ArtifactType)(0),              // 0: artifact.ArtifactType
	(*CreateArtifactRequest)(nil),  // 1: artifact.CreateArtifactRequest
	(*CreateArtifactResponse)(nil), // 2: artifact.CreateArtifactResponse
}
var file_artifact_proto_depIdxs = []int32{
	0, // 0: artifact.CreateArtifactRequest.artifact_type:type_name -> artifact.ArtifactType
	1, // 1: artifact.ArtifactStore.CreateArtifact:input_type -> artifact.CreateArtifactRequest
	2, // 2: artifact.ArtifactStore.CreateArtifact:output_type -> artifact.CreateArtifactResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_artifact_proto_init() }
func file_artifact_proto_init() {
	if File_artifact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_proto_rawDesc), len(file_artifact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifact_proto_goTypes,
		DependencyIndexes: file_artifact_proto_depIdxs,
		EnumInfos:         file_artifact_proto_enumTypes,
		MessageInfos:      file_artifact_proto_msgTypes,
	}.Build()
	File_artifact_proto = out.File
	file_artifact_proto_goTypes = nil
	file_artifact_proto_depIdxs = nil
}
