// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: network.proto

package sp1_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProofMode int32

const (
	ProofMode_UnspecifiedProofMode ProofMode = 0
	// / The core proof mode.
	ProofMode_Core ProofMode = 1
	// / The compressed proof mode.
	ProofMode_Compressed ProofMode = 2
	// / The plonk proof mode.
	ProofMode_Plonk ProofMode = 3
	// / The groth16 proof mode.
	ProofMode_Groth16 ProofMode = 4
)

// Enum value maps for ProofMode.
var (
	ProofMode_name = map[int32]string{
		0: "UnspecifiedProofMode",
		1: "Core",
		2: "Compressed",
		3: "Plonk",
		4: "Groth16",
	}
	ProofMode_value = map[string]int32{
		"UnspecifiedProofMode": 0,
		"Core":                 1,
		"Compressed":           2,
		"Plonk":                3,
		"Groth16":              4,
	}
)

func (x ProofMode) Enum() *ProofMode {
	p := new(ProofMode)
	*p = x
	return p
}

func (x ProofMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofMode) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[0].Descriptor()
}

func (ProofMode) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[0]
}

func (x ProofMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofMode.Descriptor instead.
func (ProofMode) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

type FulfillmentStrategy int32

const (
	FulfillmentStrategy_UnspecifiedFulfillmentStrategy FulfillmentStrategy = 0
	// / The hosted fulfillment strategy. Uses Succinct's on-demand prover to fulfill requests.
	FulfillmentStrategy_Hosted FulfillmentStrategy = 1
	// / The reserved fulfillment strategy. Uses an already existing agreement with a
	// / fulfiller to fulfill requests.
	FulfillmentStrategy_Reserved FulfillmentStrategy = 2
	// / The auction fulfillment strategy. Uses a decentralized proof contest to
	// / fulfill requests.
	FulfillmentStrategy_Auction FulfillmentStrategy = 3
)

// Enum value maps for FulfillmentStrategy.
var (
	FulfillmentStrategy_name = map[int32]string{
		0: "UnspecifiedFulfillmentStrategy",
		1: "Hosted",
		2: "Reserved",
		3: "Auction",
	}
	FulfillmentStrategy_value = map[string]int32{
		"UnspecifiedFulfillmentStrategy": 0,
		"Hosted":                         1,
		"Reserved":                       2,
		"Auction":                        3,
	}
)

func (x FulfillmentStrategy) Enum() *FulfillmentStrategy {
	p := new(FulfillmentStrategy)
	*p = x
	return p
}

func (x FulfillmentStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FulfillmentStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[1].Descriptor()
}

func (FulfillmentStrategy) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[1]
}

func (x FulfillmentStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FulfillmentStrategy.Descriptor instead.
func (FulfillmentStrategy) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

type MessageFormat int32

const (
	// / Unspecified message format.
	MessageFormat_UnspecifiedMessageFormat MessageFormat = 0
	// / The message is in binary format.
	MessageFormat_Binary MessageFormat = 1
	// / The message is in JSON format.
	MessageFormat_Json MessageFormat = 2
)

// Enum value maps for MessageFormat.
var (
	MessageFormat_name = map[int32]string{
		0: "UnspecifiedMessageFormat",
		1: "Binary",
		2: "Json",
	}
	MessageFormat_value = map[string]int32{
		"UnspecifiedMessageFormat": 0,
		"Binary":                   1,
		"Json":                     2,
	}
)

func (x MessageFormat) Enum() *MessageFormat {
	p := new(MessageFormat)
	*p = x
	return p
}

func (x MessageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[2].Descriptor()
}

func (MessageFormat) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[2]
}

func (x MessageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageFormat.Descriptor instead.
func (MessageFormat) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

type TransactionVariant int32

const (
	TransactionVariant_RequestVariant  TransactionVariant = 0
	TransactionVariant_BidVariant      TransactionVariant = 1
	TransactionVariant_SettleVariant   TransactionVariant = 2
	TransactionVariant_ExecuteVariant  TransactionVariant = 3
	TransactionVariant_FulfillVariant  TransactionVariant = 4
	TransactionVariant_DelegateVariant TransactionVariant = 5
	TransactionVariant_TransferVariant TransactionVariant = 6
	TransactionVariant_WithdrawVariant TransactionVariant = 7
)

// Enum value maps for TransactionVariant.
var (
	TransactionVariant_name = map[int32]string{
		0: "RequestVariant",
		1: "BidVariant",
		2: "SettleVariant",
		3: "ExecuteVariant",
		4: "FulfillVariant",
		5: "DelegateVariant",
		6: "TransferVariant",
		7: "WithdrawVariant",
	}
	TransactionVariant_value = map[string]int32{
		"RequestVariant":  0,
		"BidVariant":      1,
		"SettleVariant":   2,
		"ExecuteVariant":  3,
		"FulfillVariant":  4,
		"DelegateVariant": 5,
		"TransferVariant": 6,
		"WithdrawVariant": 7,
	}
)

func (x TransactionVariant) Enum() *TransactionVariant {
	p := new(TransactionVariant)
	*p = x
	return p
}

func (x TransactionVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[3].Descriptor()
}

func (TransactionVariant) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[3]
}

func (x TransactionVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionVariant.Descriptor instead.
func (TransactionVariant) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

type FulfillmentStatus int32

const (
	FulfillmentStatus_UnspecifiedFulfillmentStatus FulfillmentStatus = 0
	// / The request has been requested.
	FulfillmentStatus_Requested FulfillmentStatus = 1
	// / The request has been assigned to a fulfiller.
	FulfillmentStatus_Assigned FulfillmentStatus = 2
	// / The request has been fulfilled.
	FulfillmentStatus_Fulfilled FulfillmentStatus = 3
	// / The request cannot be fulfilled.
	FulfillmentStatus_Unfulfillable FulfillmentStatus = 4
)

// Enum value maps for FulfillmentStatus.
var (
	FulfillmentStatus_name = map[int32]string{
		0: "UnspecifiedFulfillmentStatus",
		1: "Requested",
		2: "Assigned",
		3: "Fulfilled",
		4: "Unfulfillable",
	}
	FulfillmentStatus_value = map[string]int32{
		"UnspecifiedFulfillmentStatus": 0,
		"Requested":                    1,
		"Assigned":                     2,
		"Fulfilled":                    3,
		"Unfulfillable":                4,
	}
)

func (x FulfillmentStatus) Enum() *FulfillmentStatus {
	p := new(FulfillmentStatus)
	*p = x
	return p
}

func (x FulfillmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FulfillmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[4].Descriptor()
}

func (FulfillmentStatus) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[4]
}

func (x FulfillmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FulfillmentStatus.Descriptor instead.
func (FulfillmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

type ExecutionStatus int32

const (
	ExecutionStatus_UnspecifiedExecutionStatus ExecutionStatus = 0
	// / The request has not been executed.
	ExecutionStatus_Unexecuted ExecutionStatus = 1
	// / The request has been executed.
	ExecutionStatus_Executed ExecutionStatus = 2
	// / The request cannot be executed.
	ExecutionStatus_Unexecutable ExecutionStatus = 3
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "UnspecifiedExecutionStatus",
		1: "Unexecuted",
		2: "Executed",
		3: "Unexecutable",
	}
	ExecutionStatus_value = map[string]int32{
		"UnspecifiedExecutionStatus": 0,
		"Unexecuted":                 1,
		"Executed":                   2,
		"Unexecutable":               3,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[5].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[5]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

type GetNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceRequest) Reset() {
	*x = GetNonceRequest{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceRequest) ProtoMessage() {}

func (x *GetNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceRequest.ProtoReflect.Descriptor instead.
func (*GetNonceRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *GetNonceRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceResponse) Reset() {
	*x = GetNonceResponse{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceResponse) ProtoMessage() {}

func (x *GetNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceResponse.ProtoReflect.Descriptor instead.
func (*GetNonceResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *GetNonceResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type RequestProofRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The account nonce of the sender.
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// / The verification key hash of the program.
	VkHash []byte `protobuf:"bytes,2,opt,name=vk_hash,json=vkHash,proto3" json:"vk_hash,omitempty"`
	// / The version of the prover to use.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// / The mode for the request.
	Mode ProofMode `protobuf:"varint,4,opt,name=mode,proto3,enum=network.ProofMode" json:"mode,omitempty"`
	// / The strategy for fulfiller assignment.
	Strategy FulfillmentStrategy `protobuf:"varint,5,opt,name=strategy,proto3,enum=network.FulfillmentStrategy" json:"strategy,omitempty"`
	// / The stdin resource identifier.
	StdinUri string `protobuf:"bytes,6,opt,name=stdin_uri,json=stdinUri,proto3" json:"stdin_uri,omitempty"`
	// / The deadline for the request.
	Deadline uint64 `protobuf:"varint,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// / The cycle limit for the request.
	CycleLimit uint64 `protobuf:"varint,8,opt,name=cycle_limit,json=cycleLimit,proto3" json:"cycle_limit,omitempty"`
	// / The gas limit for the request. If 0, the cycle_limit is used.
	GasLimit uint64 `protobuf:"varint,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// / The minimum period a request can be in auction in seconds. Zero indicates no minimum.
	MinAuctionPeriod uint64 `protobuf:"varint,10,opt,name=min_auction_period,json=minAuctionPeriod,proto3" json:"min_auction_period,omitempty"`
	// / The whitelist of provers that can bid and prove this request. An empty list indicates that
	// / any prover can participate.
	Whitelist [][]byte `protobuf:"bytes,11,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
	// / The domain separator bytes for the request.
	Domain []byte `protobuf:"bytes,12,opt,name=domain,proto3" json:"domain,omitempty"`
	// / The auctioneer address.
	Auctioneer []byte `protobuf:"bytes,13,opt,name=auctioneer,proto3" json:"auctioneer,omitempty"`
	// / The executor address.
	Executor []byte `protobuf:"bytes,14,opt,name=executor,proto3" json:"executor,omitempty"`
	// / The verifier address.
	Verifier []byte `protobuf:"bytes,15,opt,name=verifier,proto3" json:"verifier,omitempty"`
	// / The optional public values hash.
	PublicValuesHash []byte `protobuf:"bytes,16,opt,name=public_values_hash,json=publicValuesHash,proto3,oneof" json:"public_values_hash,omitempty"`
	// / The base fee for the request (string with 18 decimals).
	BaseFee string `protobuf:"bytes,17,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	// / The max price per prover gas unit for the request (string with 18 decimals).
	MaxPricePerPgu string `protobuf:"bytes,18,opt,name=max_price_per_pgu,json=maxPricePerPgu,proto3" json:"max_price_per_pgu,omitempty"`
	// / The variant of the transaction.
	Variant TransactionVariant `protobuf:"varint,19,opt,name=variant,proto3,enum=network.TransactionVariant" json:"variant,omitempty"`
	// / The treasury address.
	Treasury      []byte `protobuf:"bytes,20,opt,name=treasury,proto3" json:"treasury,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProofRequestBody) Reset() {
	*x = RequestProofRequestBody{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProofRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProofRequestBody) ProtoMessage() {}

func (x *RequestProofRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProofRequestBody.ProtoReflect.Descriptor instead.
func (*RequestProofRequestBody) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *RequestProofRequestBody) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *RequestProofRequestBody) GetVkHash() []byte {
	if x != nil {
		return x.VkHash
	}
	return nil
}

func (x *RequestProofRequestBody) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RequestProofRequestBody) GetMode() ProofMode {
	if x != nil {
		return x.Mode
	}
	return ProofMode_UnspecifiedProofMode
}

func (x *RequestProofRequestBody) GetStrategy() FulfillmentStrategy {
	if x != nil {
		return x.Strategy
	}
	return FulfillmentStrategy_UnspecifiedFulfillmentStrategy
}

func (x *RequestProofRequestBody) GetStdinUri() string {
	if x != nil {
		return x.StdinUri
	}
	return ""
}

func (x *RequestProofRequestBody) GetDeadline() uint64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *RequestProofRequestBody) GetCycleLimit() uint64 {
	if x != nil {
		return x.CycleLimit
	}
	return 0
}

func (x *RequestProofRequestBody) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *RequestProofRequestBody) GetMinAuctionPeriod() uint64 {
	if x != nil {
		return x.MinAuctionPeriod
	}
	return 0
}

func (x *RequestProofRequestBody) GetWhitelist() [][]byte {
	if x != nil {
		return x.Whitelist
	}
	return nil
}

func (x *RequestProofRequestBody) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *RequestProofRequestBody) GetAuctioneer() []byte {
	if x != nil {
		return x.Auctioneer
	}
	return nil
}

func (x *RequestProofRequestBody) GetExecutor() []byte {
	if x != nil {
		return x.Executor
	}
	return nil
}

func (x *RequestProofRequestBody) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

func (x *RequestProofRequestBody) GetPublicValuesHash() []byte {
	if x != nil {
		return x.PublicValuesHash
	}
	return nil
}

func (x *RequestProofRequestBody) GetBaseFee() string {
	if x != nil {
		return x.BaseFee
	}
	return ""
}

func (x *RequestProofRequestBody) GetMaxPricePerPgu() string {
	if x != nil {
		return x.MaxPricePerPgu
	}
	return ""
}

func (x *RequestProofRequestBody) GetVariant() TransactionVariant {
	if x != nil {
		return x.Variant
	}
	return TransactionVariant_RequestVariant
}

func (x *RequestProofRequestBody) GetTreasury() []byte {
	if x != nil {
		return x.Treasury
	}
	return nil
}

type RequestProofRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The message format of the body.
	Format MessageFormat `protobuf:"varint,1,opt,name=format,proto3,enum=network.MessageFormat" json:"format,omitempty"`
	// / The signature of the sender.
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// / The body of the request.
	Body          *RequestProofRequestBody `protobuf:"bytes,3,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProofRequest) Reset() {
	*x = RequestProofRequest{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProofRequest) ProtoMessage() {}

func (x *RequestProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProofRequest.ProtoReflect.Descriptor instead.
func (*RequestProofRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *RequestProofRequest) GetFormat() MessageFormat {
	if x != nil {
		return x.Format
	}
	return MessageFormat_UnspecifiedMessageFormat
}

func (x *RequestProofRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RequestProofRequest) GetBody() *RequestProofRequestBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type RequestProofResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TxHash        []byte                    `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Body          *RequestProofResponseBody `protobuf:"bytes,2,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProofResponse) Reset() {
	*x = RequestProofResponse{}
	mi := &file_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProofResponse) ProtoMessage() {}

func (x *RequestProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProofResponse.ProtoReflect.Descriptor instead.
func (*RequestProofResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *RequestProofResponse) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *RequestProofResponse) GetBody() *RequestProofResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type RequestProofResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestProofResponseBody) Reset() {
	*x = RequestProofResponseBody{}
	mi := &file_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProofResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProofResponseBody) ProtoMessage() {}

func (x *RequestProofResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProofResponseBody.ProtoReflect.Descriptor instead.
func (*RequestProofResponseBody) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *RequestProofResponseBody) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

type GetProofRequestStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequestStatusRequest) Reset() {
	*x = GetProofRequestStatusRequest{}
	mi := &file_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequestStatusRequest) ProtoMessage() {}

func (x *GetProofRequestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequestStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequestStatusRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

func (x *GetProofRequestStatusRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

type GetProofRequestStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The fulfillment status of the request.
	FulfillmentStatus FulfillmentStatus `protobuf:"varint,1,opt,name=fulfillment_status,json=fulfillmentStatus,proto3,enum=network.FulfillmentStatus" json:"fulfillment_status,omitempty"`
	// / The execution status of the request.
	ExecutionStatus ExecutionStatus `protobuf:"varint,2,opt,name=execution_status,json=executionStatus,proto3,enum=network.ExecutionStatus" json:"execution_status,omitempty"`
	// / The transaction hash of the request.
	RequestTxHash []byte `protobuf:"bytes,3,opt,name=request_tx_hash,json=requestTxHash,proto3" json:"request_tx_hash,omitempty"`
	// / The deadline of the request. A request should be ignored if it is past
	// / its deadline.
	Deadline uint64 `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// / The optional transaction hash of the proof fulfill. Only included if the
	// / request has a fulfillment status of FULFILLED.
	FulfillTxHash []byte `protobuf:"bytes,5,opt,name=fulfill_tx_hash,json=fulfillTxHash,proto3,oneof" json:"fulfill_tx_hash,omitempty"`
	// / The optional proof URI, where you can download the result of the request.
	// / Only included if the request has a fulfillment status of FULFILLED.
	ProofUri *string `protobuf:"bytes,6,opt,name=proof_uri,json=proofUri,proto3,oneof" json:"proof_uri,omitempty"`
	// / The optional public values hash from the execution of the request. Only
	// / included if the request has an execution status of EXECUTED.
	PublicValuesHash []byte `protobuf:"bytes,7,opt,name=public_values_hash,json=publicValuesHash,proto3,oneof" json:"public_values_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProofRequestStatusResponse) Reset() {
	*x = GetProofRequestStatusResponse{}
	mi := &file_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequestStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequestStatusResponse) ProtoMessage() {}

func (x *GetProofRequestStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequestStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProofRequestStatusResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7}
}

func (x *GetProofRequestStatusResponse) GetFulfillmentStatus() FulfillmentStatus {
	if x != nil {
		return x.FulfillmentStatus
	}
	return FulfillmentStatus_UnspecifiedFulfillmentStatus
}

func (x *GetProofRequestStatusResponse) GetExecutionStatus() ExecutionStatus {
	if x != nil {
		return x.ExecutionStatus
	}
	return ExecutionStatus_UnspecifiedExecutionStatus
}

func (x *GetProofRequestStatusResponse) GetRequestTxHash() []byte {
	if x != nil {
		return x.RequestTxHash
	}
	return nil
}

func (x *GetProofRequestStatusResponse) GetDeadline() uint64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *GetProofRequestStatusResponse) GetFulfillTxHash() []byte {
	if x != nil {
		return x.FulfillTxHash
	}
	return nil
}

func (x *GetProofRequestStatusResponse) GetProofUri() string {
	if x != nil && x.ProofUri != nil {
		return *x.ProofUri
	}
	return ""
}

func (x *GetProofRequestStatusResponse) GetPublicValuesHash() []byte {
	if x != nil {
		return x.PublicValuesHash
	}
	return nil
}

type GetProofRequestParamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The mode for the request.
	Mode          ProofMode `protobuf:"varint,1,opt,name=mode,proto3,enum=network.ProofMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequestParamsRequest) Reset() {
	*x = GetProofRequestParamsRequest{}
	mi := &file_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequestParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequestParamsRequest) ProtoMessage() {}

func (x *GetProofRequestParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequestParamsRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequestParamsRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{8}
}

func (x *GetProofRequestParamsRequest) GetMode() ProofMode {
	if x != nil {
		return x.Mode
	}
	return ProofMode_UnspecifiedProofMode
}

type GetProofRequestParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The domain separator bytes.
	Domain []byte `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// / The default auctioneer address.
	Auctioneer []byte `protobuf:"bytes,2,opt,name=auctioneer,proto3" json:"auctioneer,omitempty"`
	// / The default executor address.
	Executor []byte `protobuf:"bytes,3,opt,name=executor,proto3" json:"executor,omitempty"`
	// / The default verifier address.
	Verifier []byte `protobuf:"bytes,4,opt,name=verifier,proto3" json:"verifier,omitempty"`
	// / The default max price per prover gas unit (string with 18 decimals).
	MaxPricePerPgu string `protobuf:"bytes,5,opt,name=max_price_per_pgu,json=maxPricePerPgu,proto3" json:"max_price_per_pgu,omitempty"`
	// / The base fee for the specified proof mode (string with 18 decimals).
	BaseFee string `protobuf:"bytes,6,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	// / The default treasury address.
	Treasury      []byte `protobuf:"bytes,7,opt,name=treasury,proto3" json:"treasury,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequestParamsResponse) Reset() {
	*x = GetProofRequestParamsResponse{}
	mi := &file_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequestParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequestParamsResponse) ProtoMessage() {}

func (x *GetProofRequestParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequestParamsResponse.ProtoReflect.Descriptor instead.
func (*GetProofRequestParamsResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{9}
}

func (x *GetProofRequestParamsResponse) GetDomain() []byte {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *GetProofRequestParamsResponse) GetAuctioneer() []byte {
	if x != nil {
		return x.Auctioneer
	}
	return nil
}

func (x *GetProofRequestParamsResponse) GetExecutor() []byte {
	if x != nil {
		return x.Executor
	}
	return nil
}

func (x *GetProofRequestParamsResponse) GetVerifier() []byte {
	if x != nil {
		return x.Verifier
	}
	return nil
}

func (x *GetProofRequestParamsResponse) GetMaxPricePerPgu() string {
	if x != nil {
		return x.MaxPricePerPgu
	}
	return ""
}

func (x *GetProofRequestParamsResponse) GetBaseFee() string {
	if x != nil {
		return x.BaseFee
	}
	return ""
}

func (x *GetProofRequestParamsResponse) GetTreasury() []byte {
	if x != nil {
		return x.Treasury
	}
	return nil
}

type GetProversByUptimeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / Whether to only return high availability provers.
	HighAvailabilityOnly bool `protobuf:"varint,1,opt,name=high_availability_only,json=highAvailabilityOnly,proto3" json:"high_availability_only,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetProversByUptimeRequest) Reset() {
	*x = GetProversByUptimeRequest{}
	mi := &file_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProversByUptimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProversByUptimeRequest) ProtoMessage() {}

func (x *GetProversByUptimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProversByUptimeRequest.ProtoReflect.Descriptor instead.
func (*GetProversByUptimeRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{10}
}

func (x *GetProversByUptimeRequest) GetHighAvailabilityOnly() bool {
	if x != nil {
		return x.HighAvailabilityOnly
	}
	return false
}

type GetProversByUptimeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// / The provers that have historically had reliable uptime.
	Provers       [][]byte `protobuf:"bytes,1,rep,name=provers,proto3" json:"provers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProversByUptimeResponse) Reset() {
	*x = GetProversByUptimeResponse{}
	mi := &file_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProversByUptimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProversByUptimeResponse) ProtoMessage() {}

func (x *GetProversByUptimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProversByUptimeResponse.ProtoReflect.Descriptor instead.
func (*GetProversByUptimeResponse) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{11}
}

func (x *GetProversByUptimeResponse) GetProvers() [][]byte {
	if x != nil {
		return x.Provers
	}
	return nil
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\anetwork\"+\n" +
	"\x0fGetNonceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\"(\n" +
	"\x10GetNonceResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\xda\x05\n" +
	"\x17RequestProofRequestBody\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12\x17\n" +
	"\avk_hash\x18\x02 \x01(\fR\x06vkHash\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12&\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x12.network.ProofModeR\x04mode\x128\n" +
	"\bstrategy\x18\x05 \x01(\x0e2\x1c.network.FulfillmentStrategyR\bstrategy\x12\x1b\n" +
	"\tstdin_uri\x18\x06 \x01(\tR\bstdinUri\x12\x1a\n" +
	"\bdeadline\x18\a \x01(\x04R\bdeadline\x12\x1f\n" +
	"\vcycle_limit\x18\b \x01(\x04R\n" +
	"cycleLimit\x12\x1b\n" +
	"\tgas_limit\x18\t \x01(\x04R\bgasLimit\x12,\n" +
	"\x12min_auction_period\x18\n" +
	" \x01(\x04R\x10minAuctionPeriod\x12\x1c\n" +
	"\twhitelist\x18\v \x03(\fR\twhitelist\x12\x16\n" +
	"\x06domain\x18\f \x01(\fR\x06domain\x12\x1e\n" +
	"\n" +
	"auctioneer\x18\r \x01(\fR\n" +
	"auctioneer\x12\x1a\n" +
	"\bexecutor\x18\x0e \x01(\fR\bexecutor\x12\x1a\n" +
	"\bverifier\x18\x0f \x01(\fR\bverifier\x121\n" +
	"\x12public_values_hash\x18\x10 \x01(\fH\x00R\x10publicValuesHash\x88\x01\x01\x12\x19\n" +
	"\bbase_fee\x18\x11 \x01(\tR\abaseFee\x12)\n" +
	"\x11max_price_per_pgu\x18\x12 \x01(\tR\x0emaxPricePerPgu\x125\n" +
	"\avariant\x18\x13 \x01(\x0e2\x1b.network.TransactionVariantR\avariant\x12\x1a\n" +
	"\btreasury\x18\x14 \x01(\fR\btreasuryB\x15\n" +
	"\x13_public_values_hash\"\xa7\x01\n" +
	"\x13RequestProofRequest\x12.\n" +
	"\x06format\x18\x01 \x01(\x0e2\x16.network.MessageFormatR\x06format\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x129\n" +
	"\x04body\x18\x03 \x01(\v2 .network.RequestProofRequestBodyH\x00R\x04body\x88\x01\x01B\a\n" +
	"\x05_body\"t\n" +
	"\x14RequestProofResponse\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\fR\x06txHash\x12:\n" +
	"\x04body\x18\x02 \x01(\v2!.network.RequestProofResponseBodyH\x00R\x04body\x88\x01\x01B\a\n" +
	"\x05_body\"9\n" +
	"\x18RequestProofResponseBody\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\"=\n" +
	"\x1cGetProofRequestStatusRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\"\xae\x03\n" +
	"\x1dGetProofRequestStatusResponse\x12I\n" +
	"\x12fulfillment_status\x18\x01 \x01(\x0e2\x1a.network.FulfillmentStatusR\x11fulfillmentStatus\x12C\n" +
	"\x10execution_status\x18\x02 \x01(\x0e2\x18.network.ExecutionStatusR\x0fexecutionStatus\x12&\n" +
	"\x0frequest_tx_hash\x18\x03 \x01(\fR\rrequestTxHash\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\x04R\bdeadline\x12+\n" +
	"\x0ffulfill_tx_hash\x18\x05 \x01(\fH\x00R\rfulfillTxHash\x88\x01\x01\x12 \n" +
	"\tproof_uri\x18\x06 \x01(\tH\x01R\bproofUri\x88\x01\x01\x121\n" +
	"\x12public_values_hash\x18\a \x01(\fH\x02R\x10publicValuesHash\x88\x01\x01B\x12\n" +
	"\x10_fulfill_tx_hashB\f\n" +
	"\n" +
	"_proof_uriB\x15\n" +
	"\x13_public_values_hash\"F\n" +
	"\x1cGetProofRequestParamsRequest\x12&\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x12.network.ProofModeR\x04mode\"\xf1\x01\n" +
	"\x1dGetProofRequestParamsResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\fR\x06domain\x12\x1e\n" +
	"\n" +
	"auctioneer\x18\x02 \x01(\fR\n" +
	"auctioneer\x12\x1a\n" +
	"\bexecutor\x18\x03 \x01(\fR\bexecutor\x12\x1a\n" +
	"\bverifier\x18\x04 \x01(\fR\bverifier\x12)\n" +
	"\x11max_price_per_pgu\x18\x05 \x01(\tR\x0emaxPricePerPgu\x12\x19\n" +
	"\bbase_fee\x18\x06 \x01(\tR\abaseFee\x12\x1a\n" +
	"\btreasury\x18\a \x01(\fR\btreasury\"Q\n" +
	"\x19GetProversByUptimeRequest\x124\n" +
	"\x16high_availability_only\x18\x01 \x01(\bR\x14highAvailabilityOnly\"6\n" +
	"\x1aGetProversByUptimeResponse\x12\x18\n" +
	"\aprovers\x18\x01 \x03(\fR\aprovers*W\n" +
	"\tProofMode\x12\x18\n" +
	"\x14UnspecifiedProofMode\x10\x00\x12\b\n" +
	"\x04Core\x10\x01\x12\x0e\n" +
	"\n" +
	"Compressed\x10\x02\x12\t\n" +
	"\x05Plonk\x10\x03\x12\v\n" +
	"\aGroth16\x10\x04*`\n" +
	"\x13FulfillmentStrategy\x12\"\n" +
	"\x1eUnspecifiedFulfillmentStrategy\x10\x00\x12\n" +
	"\n" +
	"\x06Hosted\x10\x01\x12\f\n" +
	"\bReserved\x10\x02\x12\v\n" +
	"\aAuction\x10\x03*C\n" +
	"\rMessageFormat\x12\x1c\n" +
	"\x18UnspecifiedMessageFormat\x10\x00\x12\n" +
	"\n" +
	"\x06Binary\x10\x01\x12\b\n" +
	"\x04Json\x10\x02*\xb2\x01\n" +
	"\x12TransactionVariant\x12\x12\n" +
	"\x0eRequestVariant\x10\x00\x12\x0e\n" +
	"\n" +
	"BidVariant\x10\x01\x12\x11\n" +
	"\rSettleVariant\x10\x02\x12\x12\n" +
	"\x0eExecuteVariant\x10\x03\x12\x12\n" +
	"\x0eFulfillVariant\x10\x04\x12\x13\n" +
	"\x0fDelegateVariant\x10\x05\x12\x13\n" +
	"\x0fTransferVariant\x10\x06\x12\x13\n" +
	"\x0fWithdrawVariant\x10\a*t\n" +
	"\x11FulfillmentStatus\x12 \n" +
	"\x1cUnspecifiedFulfillmentStatus\x10\x00\x12\r\n" +
	"\tRequested\x10\x01\x12\f\n" +
	"\bAssigned\x10\x02\x12\r\n" +
	"\tFulfilled\x10\x03\x12\x11\n" +
	"\rUnfulfillable\x10\x04*a\n" +
	"\x0fExecutionStatus\x12\x1e\n" +
	"\x1aUnspecifiedExecutionStatus\x10\x00\x12\x0e\n" +
	"\n" +
	"Unexecuted\x10\x01\x12\f\n" +
	"\bExecuted\x10\x02\x12\x10\n" +
	"\fUnexecutable\x10\x032\xcc\x03\n" +
	"\rProverNetwork\x12?\n" +
	"\bGetNonce\x12\x18.network.GetNonceRequest\x1a\x19.network.GetNonceResponse\x12K\n" +
	"\fRequestProof\x12\x1c.network.RequestProofRequest\x1a\x1d.network.RequestProofResponse\x12f\n" +
	"\x15GetProofRequestStatus\x12%.network.GetProofRequestStatusRequest\x1a&.network.GetProofRequestStatusResponse\x12f\n" +
	"\x15GetProofRequestParams\x12%.network.GetProofRequestParamsRequest\x1a&.network.GetProofRequestParamsResponse\x12]\n" +
	"\x12GetProversByUptime\x12\".network.GetProversByUptimeRequest\x1a#.network.GetProversByUptimeResponseB\rZ\v./sp1_protob\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_network_proto_goTypes = []any{
	(ProofMode)(0),                        // 0: network.ProofMode
	(FulfillmentStrategy)(0),              // 1: network.FulfillmentStrategy
	(MessageFormat)(0),                    // 2: network.MessageFormat
	(TransactionVariant)(0),               // 3: network.TransactionVariant
	(FulfillmentStatus)(0),                // 4: network.FulfillmentStatus
	(ExecutionStatus)(0),                  // 5: network.ExecutionStatus
	(*GetNonceRequest)(nil),               // 6: network.GetNonceRequest
	(*GetNonceResponse)(nil),              // 7: network.GetNonceResponse
	(*RequestProofRequestBody)(nil),       // 8: network.RequestProofRequestBody
	(*RequestProofRequest)(nil),           // 9: network.RequestProofRequest
	(*RequestProofResponse)(nil),          // 10: network.RequestProofResponse
	(*RequestProofResponseBody)(nil),      // 11: network.RequestProofResponseBody
	(*GetProofRequestStatusRequest)(nil),  // 12: network.GetProofRequestStatusRequest
	(*GetProofRequestStatusResponse)(nil), // 13: network.GetProofRequestStatusResponse
	(*GetProofRequestParamsRequest)(nil),  // 14: network.GetProofRequestParamsRequest
	(*GetProofRequestParamsResponse)(nil), // 15: network.GetProofRequestParamsResponse
	(*GetProversByUptimeRequest)(nil),     // 16: network.GetProversByUptimeRequest
	(*GetProversByUptimeResponse)(nil),    // 17: network.GetProversByUptimeResponse
}
var file_network_proto_depIdxs = []int32{
	0,  // 0: network.RequestProofRequestBody.mode:type_name -> network.ProofMode
	1,  // 1: network.RequestProofRequestBody.strategy:type_name -> network.FulfillmentStrategy
	3,  // 2: network.RequestProofRequestBody.variant:type_name -> network.TransactionVariant
	2,  // 3: network.RequestProofRequest.format:type_name -> network.MessageFormat
	8,  // 4: network.RequestProofRequest.body:type_name -> network.RequestProofRequestBody
	11, // 5: network.RequestProofResponse.body:type_name -> network.RequestProofResponseBody
	4,  // 6: network.GetProofRequestStatusResponse.fulfillment_status:type_name -> network.FulfillmentStatus
	5,  // 7: network.GetProofRequestStatusResponse.execution_status:type_name -> network.ExecutionStatus
	0,  // 8: network.GetProofRequestParamsRequest.mode:type_name -> network.ProofMode
	6,  // 9: network.ProverNetwork.GetNonce:input_type -> network.GetNonceRequest
	9,  // 10: network.ProverNetwork.RequestProof:input_type -> network.RequestProofRequest
	12, // 11: network.ProverNetwork.GetProofRequestStatus:input_type -> network.GetProofRequestStatusRequest
	14, // 12: network.ProverNetwork.GetProofRequestParams:input_type -> network.GetProofRequestParamsRequest
	16, // 13: network.ProverNetwork.GetProversByUptime:input_type -> network.GetProversByUptimeRequest
	7,  // 14: network.ProverNetwork.GetNonce:output_type -> network.GetNonceResponse
	10, // 15: network.ProverNetwork.RequestProof:output_type -> network.RequestProofResponse
	13, // 16: network.ProverNetwork.GetProofRequestStatus:output_type -> network.GetProofRequestStatusResponse
	15, // 17: network.ProverNetwork.GetProofRequestParams:output_type -> network.GetProofRequestParamsResponse
	17, // 18: network.ProverNetwork.GetProversByUptime:output_type -> network.GetProversByUptimeResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	file_network_proto_msgTypes[2].OneofWrappers = []any{}
	file_network_proto_msgTypes[3].OneofWrappers = []any{}
	file_network_proto_msgTypes[4].OneofWrappers = []any{}
	file_network_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		EnumInfos:         file_network_proto_enumTypes,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
