use anyhow::Result;
use async_trait::async_trait;

use crate::Version;

/// Trait for zkVM provers that can generate proofs for DCAP verification.
///
/// This trait provides a common interface for different zkVM backends (RISC0, SP1, etc.)
/// to generate proofs for the DCAP attestation verification workflow.
///
/// Each prover tracks the ELF binary to use internally, which is determined at instantiation
/// time based on the DCAP deployment version.
#[async_trait]
pub trait ZkVmProver: Sized {
    /// Configuration type specific to this zkVM prover
    type Config;

    /// Create a new prover instance for a specific DCAP deployment version.
    ///
    /// # Arguments
    /// * `version` - The DCAP deployment version (v1.0, v1.1, etc.)
    ///
    /// # Returns
    /// A prover instance configured with the correct guest ELF for that version
    fn new(version: Version) -> Result<Self>;

    /// Generate a proof for the given input bytes using the specified configuration.
    ///
    /// # Arguments
    /// * `config` - zkVM-specific configuration (proving strategy, network settings, etc.)
    /// * `input_bytes` - Encoded guest input (typically `GuestInput::sol_abi_encode()`)
    ///
    /// # Returns
    /// * `(journal/public_values, seal/proof_bytes)` - The proof components:
    ///   - First element: journal (RISC0) or public values (SP1) containing the verified output
    ///   - Second element: seal (RISC0) or proof bytes (SP1) for on-chain verification
    async fn prove(&self, config: &Self::Config, input_bytes: &[u8]) -> Result<(Vec<u8>, Vec<u8>)>;

    /// Get the program identifier required by on-chain proof verification.
    ///
    /// This identifier ensures that a proof is generated by the intended guest program.
    /// Different zkVMs use different identifiers:
    /// * **RISC0**: Returns the ImageID (computed from the guest ELF)
    /// * **SP1**: Returns the verifying key hash as bytes32 string
    ///
    /// # Returns
    /// A hex string representation of the program identifier
    fn program_identifier(&self) -> Result<String>;

    /// Get the zkVM circuit version used for proof generation.
    fn circuit_version() -> String;
}
