name: Foundry Build CI/CD

on: 
    push:
        branches: [main, development]
    pull_request:
        branches: [main]

    workflow_dispatch:

env:
  DCAP_RISCZERO_IMAGE_ID: "0xb9a96822814a06ff0b7445a922946b264447676ac6a9a2e1a14179b1c3705e91"
  DCAP_SUCCINCT_VKEY: "0x00d9e1e42163e23deefcd5b7b69ed0362425aeda23a32606e499ef1736682eb3"

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run snapshot and Generate Summary
        run: NO_COLOR=1 forge snapshot --gas-report >> $GITHUB_STEP_SUMMARY